### ISSUE TITLE
Raspberry Pi - Which One

### ISSUE THREAD

**Issue by RGB-123** [Yona-Appletree/ledSPI#1]
Can you confirm which version of Raspberry Pi:
1. That this was tested to work on?
2. Which version this should work on?
3. Which OS this was tested under?

**Comment by RGB-123** [comment]
Okay, tested and loaded lastest version of Raspbian on a Raspberry pi 2 and get this error when compiling

   make: arm-linux-gnueabi-gcc: Command not found
   Makefile:55: recipe for target 'ledspi-server' failed
   make: **\* [ledspi-server] Error 127

**Comment by Yona-Appletree** [comment]
This was tested on Raspbian on a B+ 2. I've pushed a fix that will hopefully clear up your issue.

**Comment by Yona-Appletree** [comment]
This has been tested on B+ and 2 B... I welcome additional testing.

**Comment by mindforger** [comment]
i know its old but i will throw in it works on a pi zero 1.2 and 1.3 too
just if someone could give me a hint how i can let it run as a service would be nice, i executed the scripts but i lack understanding on how to properly use them to make em autorun on boot
